# Generated by Django 3.2.4 on 2021-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210609_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
    ]
